### ISSUE TITLE
Revise A/E routines

### ISSUE THREAD

**Issue by theHenks** [legend-exp/LegendSpecFits.jl#56]
Follow CM's advice and include a drift time correction in the A/E routine.
Here, in general, two options are possible:
- Do a combined fit for the Compton bands and optimize for minimal sigma function. 
- Combine all "calibrated" A/E distributions of all Compton bands and do one global `max{peak_height/fwhm}` optimization as in the CTC algorithm for the energy

In general, the routines have often times stability problems, so I think there is no way out of the combined fits. @fhagemann Can you have a look into this? 
If not, I would take care of it and then see how far I will get here. Also @LisaSchlueter might have a look here. There are definitely already code snippets available for doing such combined fits.

**Comment by theHenks** [comment]
@gipert

**Comment by gipert** [comment]
done

**Comment by theHenks** [comment]
ToDos:
- @fhagemann opens PR with changes for combined A/E compton band fits
- New routines will have `_combined` in function names
- Check if certain compton bands need to be excluded from fits based on poor perfomance (e.g. bad residuals, p-values, combination etc.)
- Implement drift time correction routine
- Compare output of new function to old method based on single peak fit
