### ISSUE TITLE
Bug fixes in LQ cut

### ISSUE THREAD

**Issue by theHenks** [legend-exp/LegendSpecFits.jl#64]
Bug fixes in `LQ` cut method needed:

- [ ] - Rename `lq_mode` in surrival fraction extractor to `inverted`
- [ ] - Make `lq` functions type stable in arguments
- [ ] - Remove hard coded detector type and introduce generic functions for fit w/o double gaussian etc.
- [ ] - Cleaner error handling
- [ ] - `Report` and `result` similar to other methods with plot recipe for `report`
- [ ] - Include `func` string which can be read by `ljlpropfunc` to generate corrected `lq` values out of dsp table

**Comment by theHenks** [comment]
CC @DaGeibl

**Comment by fhagemann** [comment]
Closed with #74
