### ISSUE TITLE
Gradient-based minimization and gradients

### ISSUE THREAD

**Issue by LisaSchlueter** [legend-exp/LegendSpecFits.jl#66]
The default algorithm of the Optim minimizer is `Nelder-Mead()`, which is a gradient-free method. I'd like to explore gradient-based algorithms, such as `GradientDescent()` or `LBFGS()`. 
Motivation:
   - We sometimes get weird fit results of calibration gamma peaks
   - When testing combined fits or comparing the different peakshape-models, the fit sometimes unreliable (local minimum?)
   - Choice of some pseudo-prior (e.g. skew fraction) have unrealistic strong impact on fit result

When going to a gradient-based algorithm, it would make sense to provide the minimizer with the analytical gradients. @oschulz 
do you have experience on how to do that in julia?

**Comment by fhagemann** [comment]
This does not work for multithreaded code.
