### ISSUE TITLE
Adjust new plot recipe (A/E combined fits)

### ISSUE THREAD

**Issue by verenaaur** [legend-exp/LegendSpecFits.jl#70]
Adjust the new plot recipe that returns the µ and σ plots with the results of the individual fits and the combined fits

- [x] change markersize
- [ ] change legend fontsize

**Comment by fhagemann** [comment]
Are we sure that this is a problem with the markersize and not with the general plot size?
Might be that if we adjust the `size` of the plot, that this will be solved right away.

**Comment by verenaaur** [comment]
The size should be the same as before but the markersize changed and I also think that the legend (aka the fontsize) is too big. I have already updated the recipe (changed the font size and the markersize), so maybe we can replace the old one in the next PR.

**Comment by fhagemann** [comment]
Sounds good!
Or just make a small PR with just these changes if you already fixed it. No need to wait for a new feature addition, PRs can be small ;)
