### ISSUE TITLE
A/E combined fits uncertainties

### ISSUE THREAD

**Issue by theHenks** [legend-exp/LegendSpecFits.jl#75]
There is a bug in the `uncertainty` calculation for the A/E combined fits. If the flag `uncertainty=true` flag is set, it throws an error because the hessian matrix cannot be calculated due to errors with `ForwardDiff`.

**Comment by fhagemann** [comment]
@theHenks is this resolved with the Zygote thing you tried out?

**Comment by theHenks** [comment]
No, apparently not. I have to do more debugging here. I also don't really understand yet why I doesn't work now, but did work before.

**Comment by theHenks** [comment]
CC @verenaaur

**Comment by theHenks** [comment]
Fixed with latest commits.
