### ISSUE TITLE
Filter Optimization flat-top Time

### ISSUE THREAD

**Issue by theHenks** [legend-exp/LegendSpecFits.jl#91]
We might have a problem with the way we handle the optimal flat-top time extraction. At the moment, we optimize a grid of flat-top time while at each step we calculate the optimal `FWHM` after `CTC`. 
However, a certain flat-top time `"threshold"` the FWHM stabilizes and doesn't change. Due to numerical issues, we sometimes pick then very big values for the flat-top time which might lead to problems in the energy extraction later. This needs further investigations.
Attached an image of one detector and its flat-top time sweep in the partition processor
 
![SCR-20241122-p1y](https://github.com/user-attachments/assets/a5c64646-d6f6-4390-88c5-34e553eb9a1b)

**Comment by LisaSchlueter** [comment]
I added a parameter `ft_fwhm_tol` with default 0.1 keV. See temp. feature branch: `filteropt_ft`. Testing in dataflow is in progress. 
![image](https://github.com/user-attachments/assets/8adea1e8-67a2-48f9-a17d-2701485025eb)
